export default {
    fips: [
        // an array of state abbreviations and their FIPS code
        { name: "AL", id: "01" },
        { name: "AK", id: "02" },
        { name: "AZ", id: "04" },
        { name: "AR", id: "05" },
        { name: "CA", id: "06" },
        { name: "LA", id: "22" },
        { name: "KY", id: "21" },
        { name: "CO", id: "08" },
        { name: "CT", id: "09" },
        { name: "DE", id: "10" },
        { name: "DC", id: "11" },
        { name: "FL", id: "12" },
        { name: "GA", id: "13" },
        { name: "HI", id: "15" },
        { name: "ID", id: "16" },
        { name: "IL", id: "17" },
        { name: "IN", id: "18" },
        { name: "IA", id: "19" },
        { name: "KS", id: "20" },
        { name: "ME", id: "23" },
        { name: "MD", id: "24" },
        { name: "MA", id: "25" },
        { name: "MI", id: "26" },
        { name: "MN", id: "27" },
        { name: "MS", id: "28" },
        { name: "MO", id: "29" },
        { name: "MT", id: "30" },
        { name: "NE", id: "31" },
        { name: "NV", id: "32" },
        { name: "NH", id: "33" },
        { name: "NJ", id: "34" },
        { name: "NM", id: "35" },
        { name: "NY", id: "36" },
        { name: "NC", id: "37" },
        { name: "ND", id: "38" },
        { name: "OH", id: "39" },
        { name: "OK", id: "40" },
        { name: "OR", id: "41" },
        { name: "PA", id: "42" },
        { name: "RI", id: "44" },
        { name: "SC", id: "45" },
        { name: "SD", id: "46" },
        { name: "TN", id: "47" },
        { name: "TX", id: "48" },
        { name: "UT", id: "49" },
        { name: "VT", id: "50" },
        { name: "VA", id: "51" },
        { name: "WA", id: "53" },
        { name: "WV", id: "54" },
        { name: "WI", id: "55" },
        { name: "WY", id: "56" },
        { name: "PR", id: "72" }
    ]
}